# Generated by Django 4.2.4 on 2023-10-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hotel_images_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
