# Generated by Django 4.2.4 on 2023-10-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hotel_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
