# Generated by Django 4.2.4 on 2023-10-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_hotel_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='place',
            new_name='hotel_place',
        ),
    ]
